format_version: 10
pipelines:
  master-ami:
    group: terraform
    materials:
      git-683112d:
        git: https://github.com/a78devops/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:wQGBZGdlHbYPyO5YwMH4ZQ==:ZcyP6UULRTBgjrVot93qp1ShNBdSQms+v0Vs/5excJg=
    stages:
      - CREATE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init"], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed}

      - DELETE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init"], run_if: passed}
                - exec: {command: terraform, arguments: [ "state", "rm", "aws_ami_from_instance.ami"], run_if: passed}
                - exec: {command: terraform, arguments: [ "destroy", "-auto-approve" ], run_if: passed}
